### ISSUE TITLE
acquiring.getCardList(request) return PAN = null

### ISSUE THREAD

**Issue by angry48** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#15]
при получении списка сохранённый карт
acquiring.getCardList(request) 
поле PAN всегда равно null

хотя сырой ответ в логе выглядит так как нужно
`[RawResponse] [{"CardId":"100000000884","Pan":"220138******0047"…"D","RebillId":"","CardType":0,"ExpDate":"1224"}]`

сам Response уже потерял значение
`[Response] [CardInfo(PAN: null, CardId: 100000000884, RebillId: , CardType: CardType.writeOffs, ExpDate: 1224, Status: CardStatus.deleted)]`

вот json полученный с сервера
`[{CardId: "100000000884", Pan: "220138******0047", Status: "D", RebillId: "", CardType: 0,…}]`

оказалось что в файле card_info.g.dart в функции CardInfo _$CardInfoFromJson(Map<String, dynamic> json)
имя написано в неверном регистре
   ` pan: json['PAN'] as String?,`
а с сервера пришло **'Pan'**

**Comment by mit-73** [comment]
Спасибо, за нахождение бага и такое подробное описание причины! Исправили в версии [3.0.3](https://pub.dev/packages/tinkoff_acquiring/versions/3.0.3).
