### ISSUE TITLE
Future not completed

### ISSUE THREAD

**Issue by angry48** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#17]
Если происходит какая-то проблема во время выполнения FinishAuthorize и возникает ошибка
`TimeoutException after 0:00:40.000000: Future not completed`
все данные полученные с сервера до приложения не доходят

[Token] {Amount: 10000, OrderId: 57475, Language: ru, CustomerKey: kultpohod_10, PayType: O, TerminalKey: TestSDK, Token: 3289b69e44b667c44659ae64fd644b5cc9cf2266d0cd0f881801dd9e8548417f}
[RawRequest] {"Amount":10000,"OrderId":"57475","Language":"ru","CustomerKey":"kultpohod_10","PayType":"O","TerminalKey":"TestSDK","Token":"3289b69e44b667c44659ae64fd644b5cc9cf2266d0cd0f881801dd9e8548417f"}
[RawResponse] {"Success":true,"ErrorCode":"0","TerminalKey":"TestSDK","Status":"NEW","PaymentId":"800000084910","OrderId":"57475","Amount":10000}
[Response] InitResponse(Success: true, Status: Status.newest, ErrorCode: 0, Message: null, Details: null, TerminalKey: TestSDK, Amount: 10000, OrderId: 57475, PaymentId: 800000084910, PaymentURL: null)
[Token] {PaymentId: 800000084910, CardData: tPJwNsDEwdC7pJGM5tGxFZbM01EQifwYVEiffKwrSdV+c7deKPfue14YjN+Gh4XgXJI26mZHx/xoqiUQX4q28yhjgiML+xL2A5AmvW0cDDBWsuTgiwdJMB3zJofLkVXaCovnPuxGc4tpaOo3T4e/yNum1NHLYt9wWGzxwXW00D/3Uy0yI+v09yd9QYYKh6Ykl1ua/4oqp0Z18btY7Gu1vmox6XaTZ7akmvpfXHq1r/hFydu7kCzq77jvhwDvAOmmYCyIHzufy67GDa1K5S2x1pLcx1ISE9s6eqMjKdIMg5uY9MQUeyGbFizD8MwhdjK6AxY4ctvXQ3Js1YnNVNDWBg==, TerminalKey: TestSDK, Token: d6cb6b058a98649f0108310f59a5c844292bf93125f37a42d7965741cdfc4be3}
[RawRequest] {"PaymentId":800000084910,"CardData":"tPJwNsDEwdC7pJGM5tGxFZbM01EQifwYVEiffKwrSdV+c7deKPfue14YjN+Gh4XgXJI26mZHx/xoqiUQX4q28yhjgiML+xL2A5AmvW0cDDBWsuTgiwdJMB3zJofLkVXaCovnPuxGc4tpaOo3T4e/yNum1NHLYt9wWGzxwXW00D/3Uy0yI+v09yd9QYYKh6Ykl1ua/4oqp0Z18btY7Gu1vmox6XaTZ7akmvpfXHq1r/hFydu7kCzq77jvhwDvAOmmYCyIHzufy67GDa1K5S2x1pLcx1ISE9s6eqMjKdIMg5uY9MQUeyGbFizD8MwhdjK6AxY4ctvXQ3Js1YnNVNDWBg==","TerminalKey":"TestSDK","Token":"d6cb6b058a98649f0108310f59a5c844292bf93125f37a42d7965741cdfc4be3"}
[RawResponse] {"Success":true,"ErrorCode":"0","Message":"OK","Version":"1.0.0"}
[Response] Check3DSVersionResponse(Success: true, Status: null, ErrorCode: 0, Message: OK, Details: null, Version: 1.0.0, TdsServerTransID: null, ThreeDSMethodURL: null)
[Token] {CardData: tPJwNsDEwdC7pJGM5tGxFZbM01EQifwYVEiffKwrSdV+c7deKPfue14YjN+Gh4XgXJI26mZHx/xoqiUQX4q28yhjgiML+xL2A5AmvW0cDDBWsuTgiwdJMB3zJofLkVXaCovnPuxGc4tpaOo3T4e/yNum1NHLYt9wWGzxwXW00D/3Uy0yI+v09yd9QYYKh6Ykl1ua/4oqp0Z18btY7Gu1vmox6XaTZ7akmvpfXHq1r/hFydu7kCzq77jvhwDvAOmmYCyIHzufy67GDa1K5S2x1pLcx1ISE9s6eqMjKdIMg5uY9MQUeyGbFizD8MwhdjK6AxY4ctvXQ3Js1YnNVNDWBg==, DATA: {}, PaymentId: 800000084910, TerminalKey: TestSDK, Token: d6cb6b058a98649f0108310f59a5c844292bf93125f37a42d7965741cdfc4be3}
[RawRequest] {"CardData":"tPJwNsDEwdC7pJGM5tGxFZbM01EQifwYVEiffKwrSdV+c7deKPfue14YjN+Gh4XgXJI26mZHx/xoqiUQX4q28yhjgiML+xL2A5AmvW0cDDBWsuTgiwdJMB3zJofLkVXaCovnPuxGc4tpaOo3T4e/yNum1NHLYt9wWGzxwXW00D/3Uy0yI+v09yd9QYYKh6Ykl1ua/4oqp0Z18btY7Gu1vmox6XaTZ7akmvpfXHq1r/hFydu7kCzq77jvhwDvAOmmYCyIHzufy67GDa1K5S2x1pLcx1ISE9s6eqMjKdIMg5uY9MQUeyGbFizD8MwhdjK6AxY4ctvXQ3Js1YnNVNDWBg==","DATA":{},"PaymentId":800000084910,"TerminalKey":"TestSDK","Token":"d6cb6b058a98649f0108310f59a5c844292bf93125f37a42d7965741cdfc4be3"}

[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: TimeoutException after 0:00:40.000000: Future not completed
[HTTP Error] TimeoutException after 0:00:40.000000: Future not completed

[RawResponse] {"Success":false,"ErrorCode":"703","Message":"Не получилось пополнить карту. Попробуйте позже","TerminalKey":"TestSDK","Status":"REJECTED","PaymentId":"800000084910","OrderId":"57475","Amount":10000}
[Response] FinishAuthorizeResponse(Success: false, Status: Status.rejected, ErrorCode: 703, Message: Не получилось пополнить карту. Попробуйте позже, Details: null, TerminalKey: TestSDK, Amount: 10000, OrderId: 57475, PaymentId: 800000084910, CardId: null, ACSUrl: null, AcsTransId: null, MD: null, PaReq: null, RebillId: null, FallbackOnTdsV1: null, TdsServerTransId: null)

**Comment by mit-73** [comment]
Здравствуйте @angry48, можете описать ваш кейс, какая происходит проблема? Приложите минимально воспроизводимый код.

[TimeoutException](https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/blob/main/packages/tinkoff_acquiring/lib/src/core/network/network_client.dart#L65) возникает лишь в том случае, если запрос (Future) не успевает обработаться в течении 40 секунд. Возможно нам стоит вынести сериализацию из этого метода...

**Comment by angry48** [comment]
Вопрос в том что бы получить данные от вашего плагина, т.к. в консоль он их пишет после сообщения о тайм-ауте

**Comment by mit-73** [comment]
@angry48 меня больше интересует как исправить этот кейс. А чтобы его исправить его нужно как минимум воспроизвести. 

Насколько я понимаю консоль он их пишет, потому-что он их завершает, но после выхода времени. А вам данные не приходят, так как там используется Completer который срабатывает в catchError быстрее чем в then...

**Comment by Shazaib-Danish** [comment]
> @angry48 меня больше интересует как исправить этот кейс. А чтобы его исправить его нужно как минимум воспроизвести.
> 
> Насколько я понимаю консоль он их пишет, потому-что он их завершает, но после выхода времени. А вам данные не приходят, так как там используется Completer который срабатывает в catchError быстрее чем в then...

Hello, I have the same issue how to solve this issue?

**Comment by mit-73** [comment]
@angry48 Исправлено в [3.0.6](https://pub.dev/packages/tinkoff_acquiring/versions/3.0.6), закрываю данную тему.
@Shazaib-Danish Fixed in [3.0.6](https://pub.dev/packages/tinkoff_acquiring/versions/3.0.6), I'm closing this thread.
