### ISSUE TITLE
Напишите в README, что требуется PCI DSS

### ISSUE THREAD

**Issue by alexeyinkin** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#19]
Для запросов, которые содеражт данные карт, Тинькофф требует PCI DSS. Как я понимаю, этот SDK можно использовать только с PCI DSS. Напишите об этом на видном месте, пожалуйста, чтобы люди без такой возможности не теряли время.

**Comment by mit-73** [comment]
Настройка PCI DSS зависит от шлюза, SDK никакого отношения к этому не имеет. Если вам необходимо изменить работу шлюза, вам необходимо обратится в тех. поддержку Тинькофф.
