### ISSUE TITLE
Расширение для маркетплейсов

### ISSUE THREAD

**Issue by Casper27th** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#21]
Здравствуйте, планируется ли расширение библиотеки для работы с маркетплейсами? Или может данная возможность уже присутствует?

**Comment by mit-73** [comment]
Здравствуйте, что вы имеете ввиду? Возможно вас интересует [параметр DATA из запроса Init](https://www.tinkoff.ru/kassa/develop/api/longpay/)?

Данный SDK реализует [API шлюза Тинкофф](https://www.tinkoff.ru/kassa/develop/api/payments/) и будет расширяться по мере расширения API.

**Comment by Casper27th** [comment]
Здравствуйте, в данном [описании документации](https://acdn.tinkoff.ru/static/documents/merchant_api_protocoI_eacq_pci_dss.pdf) при описании методов Init, Cancel, Confirm есть параметр для маркетплейсов Shops - JSON объект с данными Маркетплейса, вот этого параметра я не нашел.

**Comment by Casper27th** [comment]
Как я понял API Тинкофф не имеет данного параметра, спасибо за ответ.

**Comment by Casper27th** [comment]
В [документации](https://acdn.tinkoff.ru/static/documents/merchant_api_protocoI_eacq_pci_dss.pdf) на 12-13 страницах параметр для маркетплейс Shops описан, мы это видим и понимаем, но в описании [API ]( https://www.tinkoff.ru/kassa/develop/api/payments/init-request) во вкладке запросы об этом параметре нет ни слова.

**Comment by mit-73** [comment]
@Casper27th нам нужно изучить этот момент. Если есть такая возможность мы добавим, но думаю это будет не скоро. Если вы хотите ускорить этот вопрос, можете сами протестировать и создать PR.

**Comment by Casper27th** [comment]
@mit-73, спасибо, протестирую и дам обратную связь, очень выручили

**Comment by mit-73** [comment]
@Casper27th  Добавили Shops в [3.0.6](https://pub.dev/packages/tinkoff_acquiring/versions/3.0.6), закрываю данную тему.
