### ISSUE TITLE
Повышение безопасности (Password)

### ISSUE THREAD

**Issue by ridbrain** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#22]
Будет ли обновление до версии 2.4.0 (https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/releases/tag/v2.4.0) где "Для обеспечения безопасности SDK больше не требует пароль терминала."?

**Comment by mit-73** [comment]
@ridbrain[ на данныей момент нет](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/issues/54#issuecomment-889659015). Как только это сделают (если сделают) для бэк API, мы обновим.

**Comment by ridbrain** [comment]
Получается либо использовать их нативные сдк под (swift/kotlin), либо ваш через прокси?

**Comment by mit-73** [comment]
Если вам важна безопасность, то да.

**Comment by mit-73** [comment]
@ridbrain Добавили passwordless режим в [3.0.6](https://pub.dev/packages/tinkoff_acquiring/versions/3.0.6), закрываю данную тему.
