### ISSUE TITLE
Обновление зависимостей, WebVeiw_flutter 

### ISSUE THREAD

**Issue by Casper27th** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#24]
Здравствуйте, возникла ошибка с телефонами на Android 12, webveiw не отображает клавиатуру, нашел [решение](https://stackoverflow.com/questions/70212256/soft-keyboard-stopped-working-in-flutters-webview-on-android-12) обновление зависимостей webveiw до 3.0.0 или выше

При прохождении 3ds не появляется клавиатура, со следующей ошибкой 

I/IMM_LC  (29520): ssi() - flag : 0 view : com.example.aplication reason = SHOW_SOFT_INPUT
[        ] I/IMM_LC  (29520): ssi() view is not EditText
[        ] V/InputMethodManager(29520): b/117267690: Display ID mismatch found. ViewRootImpl displayId=42 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
[        ] V/InputMethodManager(29520): java.lang.Throwable
[        ] V/InputMethodManager(29520): 	at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:610)
[        ] V/InputMethodManager(29520): 	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1721)
[        ] V/InputMethodManager(29520): 	at android.view.inputmethod.InputMethodManager.showSoftInput(InputMethodManager.java:1703)
[        ] V/InputMethodManager(29520): 	at org.chromium.content.browser.input.ImeAdapterImpl.u(chromium-TrichromeWebViewGoogle6432.aab-stable-489612734:149)
[        ] V/InputMethodManager(29520): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(chromium-TrichromeWebViewGoogle6432.aab-stable-489612734:532)
[        ] V/InputMethodManager(29520): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] V/InputMethodManager(29520): 	at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] V/InputMethodManager(29520): 	at android.os.Looper.loopOnce(Looper.java:186)
[        ] V/InputMethodManager(29520): 	at android.os.Looper.loop(Looper.java:313)
[        ] V/InputMethodManager(29520): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
[        ] V/InputMethodManager(29520): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] V/InputMethodManager(29520): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
[        ] V/InputMethodManager(29520): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by mit-73** [comment]
Обновил в 3.0.5

https://pub.dev/packages/tinkoff_acquiring/versions/3.0.5
https://pub.dev/packages/tinkoff_acquiring_flutter/versions/3.0.5

**Comment by Casper27th** [comment]
Спасибо огромное
