### ISSUE TITLE
Получения типа карты

### ISSUE THREAD

**Issue by abdurakhmon97** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#26]
Доброго времени суток, по работе SDK никаких проблем нет, все работает как нужно. Хотел узнать, можно ли получить инфу про тип карты? MasterCard, Visa, UnionPay and etc.

**Comment by mit-73** [comment]
@abdurakhmon97 здравствуйте, очень приятно слышать!

> Можно ли получить инфу про тип карты

Да, если известны первые 4 цифры номера банковской карты (pan). Вот [метод для определения](https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/blob/main/packages/tinkoff_acquiring/lib/src/utils/card_validator.dart#L22-L45).
