### ISSUE TITLE
Invalid argument(s): `LOOP_CHECKING` is not one of the supported values

### ISSUE THREAD

**Issue by abdurakhmon97** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#27]
Доброго времени суток господа,
             Invalid argument(s): `LOOP_CHECKING` is not one of the supported values: NEW, FORM_SHOWED, DEADLINE_EXPIRED, CANCELED, PREAUTHORIZING, AUTHORIZING, AUTHORIZED, AUTH_FAIL, REJECTED, 3DS_CHECKING, 3DS_CHECKED, REVERSING, PARTIAL_REVERSED, REVERSED, CONFIRMING, CONFIRMED, REFUNDING, PARTIAL_REFUNDED, REFUNDED

Вот такую ошибку получил, когда добавил карту - удалил - снова хотел добавить ту же карту, add card resonse and attach card response пришли с success, но status:LOOP_CHECKING был

Однако, посе добавления вызывал getCardList, и добавленная карта имела статус CardStatus.deleted

**Comment by mit-73** [comment]
Здравствуйте, исправили в версии [3.0.6-dev.2](https://pub.dev/packages/tinkoff_acquiring/versions/3.0.6-dev.2), обратите внимание что это dev версия, много что там еще не тестировалось.

**Comment by mit-73** [comment]
@abdurakhmon97 Исправлено в [3.0.6](https://pub.dev/packages/tinkoff_acquiring/versions/3.0.6), закрываю данную тему.
