### ISSUE TITLE
не работает демонстрационное приложение

### ISSUE THREAD

**Issue by GreenTea000** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#28]
скопировав код из example и установив все, как указано в installing, выдает постоянно [HTTP ERROR] 'Forbidden' в консоль.

**Comment by GreenTea000** [comment]
Использовал как базовые значения TerminalKey/Password, так и свои(которые были в личном кабинете тинькофф). Нет, в консоль, т.к. пишу для flutter, выводит только [HTTP ERROR] 'Forbidden', кода ошибки нет. использую debug mode. не проходил тест кейсы из ЛК

**Comment by mit-73** [comment]
> Территориально нахожусь в РБ

Похоже в этом проблема...

```
Для возможности отправки запросов с IP-адресов, которые находятся вне РФ, напишите на почту acq_help@tinkoff.ru c просьбой добавить ваши IP в WL
```

**Comment by GreenTea000** [comment]
после добавления ip проблема не была решена. все так же ответ от сервера Forbidden

**Comment by GreenTea000** [comment]
но в письме указано не "https://rest-api-test.tcsbank.ru/", а "https://rest-api-test.tinkoff.ru/". Где можно изменить url-запрос?

**Comment by mit-73** [comment]
@GreenTea000 попробуйте использовать предварительную версию [3.0.6-dev.2](https://pub.dev/packages/tinkoff_acquiring/versions/3.0.6-dev.2), там обращение идет к `rest-api-test.tinkoff.ru`.

**Comment by GreenTea000** [comment]
поставил дев версию. Статус код ответа 403

**Comment by GreenTea000** [comment]
dev-версия заработала! спасибо Вам!
