### ISSUE TITLE
Не проходят платежи по картам МИР (например ВТБ и виртуальным картам (Сбер, Альфа))

### ISSUE THREAD

**Issue by FeofanGreek** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#45]
Здравствуйте! не во всех Android показывает экран ввода кода из СМС. В ИОС и некоторых Androidd экран показвается, но платеж не проходит. В консоли ошибка (см.вложение лога [платежа)]
![Simulator Screen Shot - iPad (10th generation) - 2023-01-19 at 08 27 07](https://user-images.githubusercontent.com/57085995/213371940-074225e1-21af-4843-911c-f6c53
![Снимок экрана 2023-01-19 в 08 52 25](https://user-images.githubusercontent.com/57085995/213375107-b597e8a2-d697-406f-b051-315b92a389cd.png)
1392363.png)
[logTinkoffAndroid.txt](https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/files/10454223/logTinkoffAndroid.txt)

[logTinkoff.txt](https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/files/10454111/logTinkoff.txt)

**Comment by putikOFF** [comment]
Специалисты Тинькофф отметили, что у них тоже была проблема с их официальным SDK для IOS, но она была решена начиная с релиза в IOS 2.13.1 
![image](https://user-images.githubusercontent.com/121632202/213660647-280ac4d1-e80c-4576-84a6-31342d420347.png)
Подозреваю, что в вашем модуле это пока не исправлено.

**Comment by mit-73** [comment]
Здравствуйте @FeofanGreek, я проверил изменения и не нашел ничего глобального отличающего от нашей реализации. Не могли бы вы узнать что конкретно поменялось в версии `2.13.1`. Если что наш SDK работает на api протоколе EACQ C PCI DSS.

**Comment by putikOFF** [comment]
> Здравствуйте@FeofanGreek, я заразился изменениями и не нашел ничего глобально отличающегося от нашей реализации. Не могли бы вы узнать, что конкретно поменялось в версии `2.13.1`. Если наш SDK работает на протоколе API EACQ C PCI DSS.

Ответ от ТП Тинкофф:
В версии 2.13.1 в ASDK была исправлена ошибка, когда карты МИР при привязки проходили проверку только по 3ds v1.0. Сейчас ASDK использует метод для распознавания версии 3ds и проводит проверку по 3ds v2.0

**Comment by putikOFF** [comment]
Привет @mit-73.
Вот еще от службы ТП Тирнькофф дополнение:
Александр, здравствуйте!
Пишу вам по вопросу оплаты картами МИР в мобильном приложении.
Как говорили мои коллеги ранее, проблема возникала из-за того, что в системе МИР произошел переход на версию 3DS 2.0 и в случае с работой по API с PCI DSS, есть метод для проверки версии  3DS(важно, чтобы версии совпадали).
В обновлении SDK для IOS было исправление, в рамках которого исправили момент с определением версии 3DS и дальнейшей работы платежей по картам МИР, поэтому можно обновить/установить SDK для IOS версией 2.13.1 и выше, чтобы все работало корректно. 
Обычно, при оплате в таком случае, вызывается окно с платежной формой, где покупатель оплачивает(пример на скриншоте). Это работает при использовании нашего SDK. 
В случае, если вы используете API с PCI DSS, могу предложить вам документацию:
[https://acdn.tinkoff.ru/static/documents/merchantapiprotocoIeacqpci_dss.pdf](https://acdn.tinkoff.ru/static/documents/merchant_api_protocoI_eacq_pci_dss.pdf)
Там описаны методы для проверки версии 3DS. В случае использования PCI DSS, вам понадобится метод Check3dsVersion, там подробно описаны сценарии в зависимости от версии 3DS.

**Comment by mit-73** [comment]
@FeofanGreek @putikOFF здравствуйте, попытались исправить проблему, но на тестовом шлюзе не получиться ее протестировать до конца. Прошу вас протестировать работоспособность на ваших шлюзах, ветка с исправлениями: [3ds_fix](https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/tree/3ds_fix).

В `FinishAuthorizeRequest` поле `ip` необходимо для прохождения 3DS 2.0, вы можете использовать метод `await getIpAddress()` для получения полного ip адреса.

**Comment by FeofanGreek** [comment]
Здравствуйте! пробую подключить библиотеку 
tinkoff_acquiring:
    git:
      url: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter.git
      ref: 3ds_fix
получаю ошибочку Could not find a file named "pubspec.yaml" in https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter.git e402ff10fe7bf7595bcaf4cfa0cfdbd2cc2a81a5.
pub get failed

**Comment by mit-73** [comment]
Попробуйте так:
```
tinkoff_acquiring:
  git:
    url: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter.git
    ref: 3ds_fix
    path: packages/tinkoff_acquiring
```

**Comment by FeofanGreek** [comment]
Running "flutter pub get" in storagewires...
Resolving dependencies...
Because tinkoff_acquiring_flutter 3.0.9 depends on tinkoff_acquiring ^3.0.9 and no versions of tinkoff_acquiring_flutter match >3.0.9 <4.0.0, tinkoff_acquiring_flutter ^3.0.9 requires tinkoff_acquiring from hosted.
So, because storagewires depends on both tinkoff_acquiring from git and tinkoff_acquiring_flutter ^3.0.9, version solving failed.
pub get failed
command: "/Users/*****/development/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/*****/development/flutter",
  "PUB_ENVIRONMENT": "flutter_cli:get",
  "PUB_CACHE": "/Users/*****/.pub-cache",
}
exit code: 1

Process finished with exit code 1

**Comment by FeofanGreek** [comment]
Если убираю  tinkoff_acquiring_flutter ^3.0.9 из pubsec  в коде становятся ошибочными: CollectData(
        context: context,
        config: acquiring.config,
        serverTransId: check3DSVersion.serverTransId!,
        threeDsMethodUrl: check3DSVersion.threeDsMethodUrl!,
        onFinished: (Map<String, String> v) {
          data.complete(v);
        },
      );
WebView3DS(
            config: acquiring.config,
            //is3DsVersion2: fa.is3DsVersion2 || check3DSVersion.is3DsVersion2,
            //serverTransId: fa.tdsServerTransId ?? check3DSVersion.serverTransId, ///serverTransId изменился тип версии
            is3DsVersion2: check3DSVersion.is3DsVersion2,
            serverTransId: check3DSVersion.serverTransId,
            acsUrl: fa.acsUrl!,
            md: fa.md,
            paReq: fa.paReq,
            acsTransId: fa.acsTransId,
            version: check3DSVersion.version,
            onLoad: (bool v) {
              debugPrint('WebView load: $v');
            },
            onFinished: (Submit3DSAuthorizationResponse? v) {
              Navigator.of(context).pop();
              webView.complete(v);
            },
          ),

**Comment by mit-73** [comment]
```
dependencies:
  flutter:
    sdk: flutter

  tinkoff_acquiring: ...
  tinkoff_acquiring_flutter: ...

dependency_overrides:
  tinkoff_acquiring:
    git:
      url: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter.git
      ref: 3ds_fix
      path: packages/tinkoff_acquiring
  tinkoff_acquiring_flutter:
    git:
      url: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter.git
      ref: 3ds_fix
      path: packages/tinkoff_acquiring_flutter
```

**Comment by FeofanGreek** [comment]
Пакеты, забрал, спасибо! Сейчас будем тестить

**Comment by FeofanGreek** [comment]
Все заработало! В тестовом пакете платежи по картам Мир и другим системам прошли без проблем. Спасибо!

**Comment by FeofanGreek** [comment]
Ждем боевой версии

**Comment by mit-73** [comment]
Выпустил новую версию в pub.dev
