### ISSUE TITLE
Чёрный экран после подтверждения оплаты

### ISSUE THREAD

**Issue by freerunningpanda** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#46]
Здравствуйте уважаемые разработчики!

Мы столкнулись с такой проблемой, после оплаты в приложении деньги списываются, далее мы видим чёрный экран. Но если повторить процедуру второй раз, то всё проходит нормально. Не ясно из-за чёрного экрана, прошла оплата или нет. 
В чём может быть ошибка?

**Comment by mit-73** [comment]
Здравствуйте, в какой момент происходит черный экран? У вас происходит навигация перед показом черного экрана?

**Comment by mit-73** [comment]
Похоже вы забыли добавить переход после прохождения проверки 3ds, посмотрите [пример](https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/blob/dev/example/lib/main.dart#L295-L296).

**Comment by halahot** [comment]
@mit-73 здравствуйте! Имею схожую проблему. Но у меня эти параметры возвращаются null 
`Check3DSVersionResponse(Success: true, Status: null, ErrorCode: 0, Message: OK, Details: null, Version: 1.0.0, TdsServerTransID: null, ThreeDSMethodURL: null, PaymentSystem: null)`
Может быть это от того что я инициализирую платеж на беке?
