### ISSUE TITLE
Белый экран после подтверждения платежа

### ISSUE THREAD

**Issue by halahot** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#49]
Здравствуйте, уважаемые разработчики! Помогите пожалуйста с проблемой. Подскажите что не так?

Реализую оплату как в примере но при возврате с вебвью получаю белый экран с объектом Submit3DSAuthorizationResponse как будто но не происходит редиректа обратно в приложени. Параметры указанные тут https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/issues/46#issuecomment-1401386446 я передаю но они почему то возвращаются мне как null при проверке check3DSVersion
`Check3DSVersionResponse(Success: true, Status: null, ErrorCode: 0, Message: OK, Details: null, Version: 1.0.0, TdsServerTransID: null, ThreeDSMethodURL: null, PaymentSystem: null)`

![image](https://user-images.githubusercontent.com/22423825/219349823-061abadb-11b3-4d65-b3ef-6b40c151f2ac.png)

PS: если отменяешь проверку 3DS то на такой же белый экран редиректит

**Comment by mit-73** [comment]
Здравствуйте, покажите код WebView3DS, а именно: https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/blob/dev/example/lib/main.dart#L336-L339

**Comment by halahot** [comment]
`onFinished: (Submit3DSAuthorizationResponse? v) {
                      bloc?.add(Confirm3dsEvent(fa.status));
                      webView.complete(v);
                      Navigator.of(context).pop();
                    },
`

**Comment by mit-73** [comment]
@halahot проверьте работу `Navigator.of(context).pop();`, возможно у вас поверх еще что-то открывается и нужно выполнить `pop` два раза, либо вы открывали этот экран через `rootNavigator`, тогда закрывать нужно так: `Navigator.of(context, rootNavigator: true).pop();`

**Comment by halahot** [comment]
На любые попытки закрыть этими способами получаю 
`Failed assertion: line 4516 pos 12: '!_debugLocked': is not true.`

**Comment by halahot** [comment]
И еще на некоторых картах не отрабатывает метод onFinished при отмене ввода кода
PS: на картах МИР
