### ISSUE TITLE
Зависимости

### ISSUE THREAD

**Issue by sergeyshaklein** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#5]
При попытке добавить 
dependencies: 
tinkoff_acquiring: 1.0.2

Because Project depends on tinkoff_acquiring 1.0.2 which depends on webview_flutter ^1.0.5, webview_flutter ^1.0.5 is required.
So, because Project depends on webview_flutter 2.0.1, version solving failed.

**Comment by mit-73** [comment]
Проблема связанна с разными версиями `webview_flutter`. В `tinkoff_acquiring `используется `1.0.5`, а у вас в проекте есть зависимость с версией `2.0.1`.
На данные момент мы работаем над миграции пакета на версию с null safe (Flutter 2), после чего обновим эту зависимость.

Чтобы решить вашу проблему, вы можете сделать следующие: добавить в `pubspec.yaml` поле [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides)

```yaml
dependency_overrides:
  webview_flutter : ^2.0.1
```

Я не гарантирую что у вас будет работать часть библиотеки связанной с `tinkoff_acquiring_ui`, но вы точно сможете использовать `tinkoff_acquiring_core `(правда без поддержки null safe)

**Comment by mit-73** [comment]
@sergeyshaklein обновили библиотеку (#6) до версии `2.0.0` в pub. Там произошли некоторые изменения, будте внимательны.
Я закрываю этот вопрос.
