### ISSUE TITLE
Не работает отмена в веб-форме 3ds v2

### ISSUE THREAD

**Issue by alex-dorokhov** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#7]
Спасибо за библиотеку, весьма полезна, особенно функция проксирования запросов.

Тестирую последнюю версию с помощью встроенного примера и stable версии flutter (2.0.5).
1. Включаю 3ds v2.
2. Ожидаю появления веб-формы для ввода кода.
3. Нажимаю "Отмена", но ожидаемой реакции на нажатие не происходит (закрытие веб-формы).

В консоли выводится следующее сообщение:
```
W/cr_WebViewCallback( 3575): Unable to create JsDialog without an Activity
E/InputMethodManager( 3575): b/117267690: Failed to get fallback IMM with expected displayId=28 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{db26a0b VFEDHVC.. .F...... 0,0-1080,2154}
```

Предполагаю, что связано с тем что страница пытается использовать браузеровский _window.alert_ для отображения окна подтверждения. Вероятно связано с этим багом: https://github.com/flutter/flutter/issues/30358 .

В целом так же хотелось бы иметь и какой-то колбэк / результат от CollectData, указывающий, что пользователь отменил процесс оплаты (и соответственно платежная сессия должна быть закрыта в использующем приложении).

![device-2021-04-19-215625](https://user-images.githubusercontent.com/788340/115295560-8d095c80-a162-11eb-9a3b-09cf8503c809.png)

**Comment by mit-73** [comment]
Здравствуйте @alex-dorokhov, да мы знаем о данной проблеме.
Она связанно с багом flutter/flutter#30358, но отличается тем что там используется своя реализация `alert`, которую не удается поймать с помощью  `JavascriptChannel`.

На данный момент есть способ как это исправить на android:
```
if (defaultTargetPlatform == TargetPlatform.android) {
    WebView.platform = SurfaceAndroidWebView();
}
```
Но к сожалению с ios такое не пройдет...


> В целом так же хотелось бы иметь и какой-то колбэк / результат от CollectData, указывающий, что пользователь отменил процесс оплаты (и соответственно платежная сессия должна быть закрыта в использующем приложении).

Вы скорее всего путаете `CollectData` с `WebView3DS`, так как `CollectData` не показывает WebView с 3DS проверкой.
Когда происходит отмена проверки 3DS `WebView3DS` [вызывает колбэк `onFinished`](https://github.com/MadBrains/Tinkoff-Acquiring-SDK-Flutter/blob/main/lib/src/ui/web_view_3ds.dart#L140) с `null` параметром.


Если у вас есть решение данной проблемы, мы открыты к PR.

**Comment by mit-73** [comment]
Закрываю данный вопрос, так как нет активности.
