### ISSUE TITLE
Что из себя представляет аргумент для параметра encryptedPaymentData

### ISSUE THREAD

**Issue by russmvr** [MadBrains/Tinkoff-Acquiring-SDK-Flutter#9]
Добрый день. Мне предстоит подключить google pay и apple pay. И я в этом вопросе немного новичок, поскольку с этим дел не имел и понятной, четкой информации по A/G pay крайне мало, в том числе официальной. Наткнувшись на ваш пост на хабре, был очень рад что нашел ваш вас: https://habr.com/ru/company/tinkoff/blog/544080/
Так вот, у меня есть небольшой вопрос. 
Можете пожалуйста подсказать, что представляет из себя аргумент для параметра encryptedPaymentData, где его взять и как он выглядит.
Я немного дезориентирован этим, из-за этого уже стою на месте пару дней. 
Буду очень благодарен вашему ответу!

![Screenshot_70](https://user-images.githubusercontent.com/74022708/117570080-8e7ad480-b0d1-11eb-80c9-079c67650b01.png)

**Comment by mit-73** [comment]
Здраствуйте @russmvr, `encryptedPaymentData` это зашифрованная строка токена в формате `base64` полученная из [google pay](https://developers.google.com/pay/api/android/reference/response-objects?hl=ru#PaymentMethodTokenizationData) и [apple pay](https://developer.apple.com/documentation/passkit/pkpaymenttoken/1617000-paymentdata).

Чтобы получить токен, вы можете воспользоваться библиотекой [mad_pay](https://pub.dev/packages/mad_pay):

```
final MadPay pay = MadPay();
final PaymentResponse payment = await pay.processingPayment(...);
final String encryptedPaymentData = base64.encode(utf8.encode(payment.token));
```

**Comment by russmvr** [comment]
Большое спасибо
